---
- name: Tune sysctl parameters
  hosts: servers
  become: true
  tasks:
    - name: Set vm.swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "10"
        state: present
        sysctl_set: true
        reload: true

    - name: Set net.ipv4.ip_forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "0"
        state: present
        sysctl_set: true
        reload: true
